spring.application.name=mascotas-cordoba-project

# Server Port
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=das;encrypt=false
spring.datasource.username=admin
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Security API Keys (Support Environment Variables with defaults)
security.soap.api-key=${SOAP_API_KEY:UBPqnXyjsMPkbYN4Qj1ag3zveiimsMAPjyT}
security.rest.api-key=${REST_API_KEY:UBPU5i0Kq7Cne3p3mzdrwEpBj7XyQsaiXq6}

# Apache CXF Base URL for SOAP
cxf.path=/services